name: Semgrep - SAST Scan

on:
  pull_request:
    types: [ closed, edited, opened, synchronize, ready_for_review ]

permissions:
  contents: read

jobs:
  semgrep:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Semgrep SAST Scan
        run: semgrep scan --config p/default --metrics=off --sarif --sarif-output=results.sarif --baseline-commit "${{ github.event.pull_request.base.sha }}"

      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
